### ISSUE TITLE
Access to the path 'D:\dev\nuget\packages' is denied

### ISSUE THREAD

**Issue by gillus123** [lithnet/windows-credential-provider#6]
Hi,
Thank you for the Credential Provider, I just opened it with latest VS Community and Pro 2022 editions and I have the same error:
<img width="1242" alt="image" src="https://github.com/lithnet/windows-credential-provider/assets/71516624/328e742c-65f7-4ba5-a9a2-bee6a2633a17">
Any idea?
All my Nuget Packages are up-to-date, I also tried:
TOOLS -> Options -> NuGet Package Manager -> General ==> Clear All NuGet Cache(s)” button.
Doesn't change....
BR

**Comment by ryannewington** [comment]
Hi @gillus123 

Are you looking to modify the credential provider code? Or do you just want to create a credential provider using the library?

If your looking to modify the code for the library itself, you just need to clear the package path element in the csproj file.

Otherwise you don't need to open the library code, just install the Lithnet.CredentialProvider NuGet package into your solution

**Comment by gillus123** [comment]
Hello,
Thank you, I can build it now.
I am not very familiar with .NET technos, I didn't notice the .vcproj files were discarded by Visual Studio after loading the project.
Cheers
